// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react'
import { HelmetProvider } from '/Users/chenkl/Desktop/meitu/tool-helper/docs/node_modules/@umijs/renderer-react'
import { context } from './helmetContext'

export const innerProvider = (container) => {
  return React.createElement(HelmetProvider, { context }, container)
}
