// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/chenkl/Desktop/meitu/tool-helper/docs/node_modules/dumi/theme-default/slots/PreviewerActions/index.js'
