// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react'
import { useOutlet, history } from 'dumi'
import { SiteContext } from '/Users/chenkl/Desktop/meitu/tool-helper/docs/node_modules/dumi/dist/client/theme-api/context.js'
import { demos, components } from '../meta'
import { locales } from '../locales/config'

const entryExports = {}

export default function DumiContextWrapper() {
  const outlet = useOutlet()
  const [loading, setLoading] = useState(false)
  const prev = useRef(history.location.pathname)

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0)
      }
    })
  }, [])

  return (
    <SiteContext.Provider
      value={{
        pkg: {
          name: '',
          description: 'A static site based on dumi',
          version: '0.0.1',
          license: 'MIT',
          authors: []
        },
        historyType: 'browser',
        entryExports,
        demos,
        components,
        locales,
        loading,
        setLoading,
        hostname: undefined,
        themeConfig: {
          footer:
            'Copyright © 2023 | Powered by <a href="https://d.umijs.org" target="_blank" rel="noreferrer">dumi</a>',
          prefersColor: { default: 'light', switch: true },
          nprogress: true,
          lastUpdated: true,
          name: ''
        },
        _2_level_nav_available: true
      }}
    >
      {outlet}
    </SiteContext.Provider>
  )
}
