// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports'
export * from '/Users/chenkl/Desktop/meitu/tool-helper/docs/node_modules/dumi/dist/client/theme-api/index.js'
